---
globals:
  polybar_config: /home/s0001604/.config/polybar/config.ini
  warpd_config: /home/s0001604/programs/warpd/src/config.c
  dmenu_config: /home/s0001604/programs/dmenu-5.2/config.h
  kitty_config: /home/s0001604/.config/kitty/kitty.conf
  dunst_config: /home/s0001604/.config/dunst/dunstrc
  i3_config: /home/s0001604/.config/i3/config
  themifier_dir: /home/s0001604/.config/themifier
components:
  - background:
    enabled: true
    cmd: feh --bg-fill <background>

  - polybar:
    enabled: true
    substitutions:
      engine: perl
      changes:
        - ['(?<=background = #).*', <color0>, <polybar_config>]
        - ['(?<=alert = #).*', <color1>, <polybar_config>]
        - ['(?<=statusline = #).*', <statusline1>, <polybar_config>]
        - ['(?<=primary = #).*', <color3>, <polybar_config>]
        - ['(?<=seconday = #).*', <color4>, <polybar_config>]
        - ['(?<=foreground = #).*', <color7>, <polybar_config>]

  - warpd:
    enabled: true
    substitutions:
      engine: perl
      changes:
        - ['(?<=red_color., .#).{6}', <color1>, <warpd_config>]
        - ['(?<=green_color., .#).{6}', <color2>, <warpd_config>]
        - ['(?<=yellow_color., .#).{6}', <color3>, <warpd_config>]
        - ['(?<=blue_color., .#).{6}', <color4>, <warpd_config>]
        - ['(?<=gray_color., .#).{6}', <color7>, <warpd_config>]

  - dmenu:
    enabled: true
    substitutions:
      engine: perl
      changes:
        - ['(?<=SchemeNorm].{3,8})[0-9a-fA-F]{6}', <color7>, <dmenu_config>]
        - ['(?<=SchemeNorm].{13,20})[0-9a-fA-F]{6}', <color0>, <dmenu_config>]
        - ['(?<=SchemeSel].{3,8})[0-9a-fA-F]{6}', <color0>, <dmenu_config>]
        - ['(?<=SchemeSel].{13,20})[0-9a-fA-F]{6}', <statusline1>, <dmenu_config>]
        - ['(?<=SchemeOut].{3,8})[0-9a-fA-F]{6}', <color7>, <dmenu_config>]
        - ['(?<=SchemeOut].{13,20})[0-9a-fA-F]{6}', <color4>, <dmenu_config>]
        - ['(?<=SchemeSelHighlight].{3,8})[0-9a-fA-F]{6}', <color3>, <dmenu_config>]
        - ['(?<=SchemeSelHighlight].{13,20})[0-9a-fA-F]{6}', <statusline1>, <dmenu_config>]
        - ['(?<=SchemeNormHighlight].{3,8})[0-9a-fA-F]{6}', <color3>, <dmenu_config>]
        - ['(?<=SchemeNormHighlight].{13,20})[0-9a-fA-F]{6}', <color0>, <dmenu_config>]
        
  - kitty:
    enabled: true
    substitutions:
      engine: perl
      changes:
        - ['(?<=background_opacity ).{3}', <transparency>, <kitty_config>]
        - ['(?<=color0 #)[0-9a-fA-F]{6}', <color0>, <kitty_config>]
        - ['(?<=color1 #)[0-9a-fA-F]{6}', <color1>, <kitty_config>]
        - ['(?<=color2 #)[0-9a-fA-F]{6}', <statusline1>, <kitty_config>]
        - ['(?<=color3 #)[0-9a-fA-F]{6}', <color3>, <kitty_config>]
        - ['(?<=color4 #)[0-9a-fA-F]{6}', <color4>, <kitty_config>]
        - ['(?<=color5 #)[0-9a-fA-F]{6}', <color5>, <kitty_config>]
        - ['(?<=color6 #)[0-9a-fA-F]{6}', <color6>, <kitty_config>]
        - ['(?<=color7 #)[0-9a-fA-F]{6}', <color7>, <kitty_config>]
        - ['(?<=background #)[0-9a-fA-F]{6}', <color0>, <kitty_config>]
        - ['(?<=foreground #)[0-9a-fA-F]{6}', <color7>, <kitty_config>]

  - dunst:
    enabled: false
    substitutions:
      engine: perl
      changes:
        - ['(?<=foreground = .#)[0-9a-fA-F]{6}', <color7>, <dunst_config>]

  - neovim:
    enabled: true
    substitutions:
      engine: perl
      changes:
        - ['(?<=colorscheme = .)[a-z]{4,15}', <nvim_colorscheme>, /home/s0001604/.config/nvim/lua/user/init.lua]
        - ['(?<=local source = .).{1,40}\.png', <nvim_logo>, /home/s0001604/.local/share/nvim/lazy/alpha-nvim/lua/alpha.lua]

  - chrome:
    enabled: false
    cmd: <themifier_dir>/scripts/update_chrome.sh <chrome_theme>
    # todo: generate chrome theme from theme.yaml
    # todo: write script to update chrome theme

  - gtk:
    enabled: true
    cmd: gsettings set org.gnome.desktop.interface gtk-theme <gtk_theme>
    # todo: generate gtk-theme from theme.yaml

  - slack:
    enabled: false

  - obsidian:
    enabled: false

  - i3:
    enabled: true
    substitutions:
      engine: perl
      changes:
        - ['(?<=client.focused {11}).+$', '#<statusline1> #<color0> #<color7> #<color0>', <i3_config>]
        - ['(?<=client.unfocused {9}).+$','#<border> #<color0> #<color8> #<color0>', <i3_config>]
        - ['(?<=client.focused_inactive  ).+$','#<border> #<color0> #<color8> #<color0>', <i3_config>]
        - ['(?<=client.placeholder {7}).+$','#<border> #<color0> #<color8> #<color0>', <i3_config>]
        - ['(?<=client.urgent {12}).+$', '#<color1> #<color1> #<color7> #<color1>', <i3_config>]
        - ['(?<=client.background {8}).+$', '#<color0>', <i3_config>]

  - picom:
    enabled: false

  - recompile:
    enabled: true
    cmd: <themifier_dir>/scripts/recompile.sh

  - restart_kitty:
    enabled: true
    cmd: xdotool key Ctrl+Shift+F5
